#ifndef COMMON_CONSTANTS_H_
#define COMMON_CONSTANTS_H_

#define MBM_VERSION "0.5"
#define READY       "READY"
#define END         "END"

#define MS_PER_SEC  1000
#define NS_PER_SEC  1000000000
#define MAX_PACKETS_TEST 30000
#define MAX_PACKETS_CWND 30000
#define TEST_BASE_SEC 30
#define TEST_INCR_SEC_PER_MB 15
#define CWND_BASE_SEC 30
#define CWND_INCR_SEC_PER_MB 5

#define SEED 132315
#endif  // COMMON_CONSTANTS_H_
