#ifndef COMMON_CONSTANTS_H_
#define COMMON_CONSTANTS_H_

#define MBM_VERSION "0.5"
#define READY       "READY"

#define MS_PER_SEC  1000
#define NS_PER_SEC  1000000000
#define TOTAL_PACKETS_TO_SEND 30

#endif  // COMMON_CONSTANTS_H_
